#!/usr/bin/env python3
"""Read-only, de-identified classification of unmatched reference preview rows.

Classification is a research annotation, never deletion authority. No filesystem
measurement or cleanup is performed. Unknown entries stay unresolved. Preview
sizes are rounded and may overlap; they are not verified reclaimable bytes.
"""
import argparse
from collections import Counter
import hashlib
import json
from pathlib import Path

from cleanup_coverage_audit import compare, parse_reference_preview


FIXED = {
    "Library/Caches/com.apple.python/Users": ("Python generated cache (user tree)", "python", "candidate", "Verify generated bytecode and active-owner boundaries"),
    "Library/Caches/com.apple.python/Library": ("Python generated cache (library tree)", "python", "candidate", "Verify generated bytecode and active-owner boundaries"),
    "Library/Logs/DiagnosticReports": ("Diagnostic reports", "diagnostics", "protected", "Retain diagnostic retention policy"),
    "Library/Logs/CrashReporter": ("Crash reports", "diagnostics", "protected", "Retain diagnostic retention policy"),
    "Library/Application Support/Google/GoogleUpdater/crx_cache/metadata.json": ("Browser updater metadata", "updater", "unresolved", "Prove updater ownership and metadata lifetime"),
    ".oh-my-zsh/cache/grep-alias": ("Shell cached alias", "shell", "unresolved", "Distinguish executable shell content from disposable data"),
    ".oh-my-zsh/cache/completions": ("Shell completion cache", "shell", "candidate", "Verify generated completion data without touching configuration"),
}
for name in ("HSTS.plist", "HelpCache.plist", "CSHelpIndex.plist"):
    FIXED[f"Library/Caches/com.apple.helpd/{name}"] = (
        f"Help Viewer {name}", "help_viewer", "protected", "Keep metadata outside supported page/generated subtrees",
    )
for name in ("Metrics", "DynamicUI", "Engagement"):
    FIXED[f"Library/Caches/com.apple.AppleMediaServices/{name}"] = (
        f"Media service {name}", "media_service", "unresolved", "Establish an owner and regenerability contract",
    )
for name in (
    "bag.plist", "CustomFeedback", "silhouette_config", "correction_dict_url",
    "spotlight_stopword.map", "dictionary_resources_url", "silhouette_topic_mapping",
    "spotlight_model_resources", "autofill_tld_whitelist_url", "crowdsourcing_blacklist_url",
    "crowdsourcing_whitelist_url", "installed_app_whitelist_url", "silhouette_whitelisted_topics",
    "spotlight_phrase_dictionary.map",
):
    protected = name in ("bag.plist", "silhouette_config", "CustomFeedback")
    FIXED[f"Library/Caches/com.apple.parsecd/{name}"] = (
        f"Search service {name}", "search_service", "protected" if protected else "unresolved",
        "Preserve configuration/feedback" if protected else "Prove exact resource is reproducible; do not clear service root",
    )
for relative, label, family in (
    ("Library/Caches/pnpm", "pnpm cache alias", "javascript"),
    ("Library/Caches/gopls", "gopls cache", "go"),
    ("Library/Caches/goimports", "goimports cache", "go"),
    ("Library/Caches/dotslash", "DotSlash cache", "toolchain"),
    ("Library/Caches/SentryCrash", "Crash SDK cache", "diagnostics"),
    ("Library/Caches/com.zenith.desktop", "Zenith cache", "application"),
    ("Library/Logs/SiriTTSService", "Speech-service logs", "diagnostics"),
    ("Library/Caches/dev.warp.Warp-Stable/async.log", "Terminal log", "application"),
    ("Library/Caches/dev.warp.Warp-Stable/io.sentry", "Terminal telemetry cache", "application"),
):
    FIXED[relative] = (label, family, "unresolved", "Recheck nonzero presence and existing owner coverage")


def classify(path, home, preview_bytes):
    prefix = home.rstrip("/") + "/"
    relative = path[len(prefix):] if path.startswith(prefix) else None
    rule = FIXED.get(relative)
    if relative and relative.startswith(".zcompdump-") and "/" not in relative:
        rule = ("Compiled shell completion dump" if relative.endswith(".zwc") else "Shell completion dump",
                "shell", "candidate", "Verify generated completion data and shell activity")
    label, family, decision, action = rule or (
        "Unclassified preview entry", "unknown", "unresolved", "Manual source review required",
    )
    # Zero is only what the historical rounded preview displayed, not proof
    # that a live path is absent, fully measured, or safe to delete.
    return {
        "label": label, "family": family, "classification": decision,
        "preview_zero": preview_bytes == 0,
        "confidence": "source_review" if rule else "unresolved",
        "next_action": action,
    }


def build_ledger(reference, zenith_rows, home):
    _, relationships, _, details, overlaps = compare(reference, zenith_rows, home, False)
    rows = []
    for row in details:
        if row["relation"] != "reference_only":
            continue
        relative = row["path"].removeprefix(home.rstrip("/") + "/")
        rows.append({
            "candidate_id": hashlib.sha256(relative.encode()).hexdigest()[:16],
            **classify(row["path"], home, row["displayed_bytes"]),
            "relationship": "reference_only",
            "rounded_preview_bytes": row["displayed_bytes"],
            "verified_reclaim_bytes": None,
            "execution_policy": "not_authorized_by_this_report",
            "overlaps_another_preview": any(
                row["path"].startswith(other["path"].rstrip("/") + "/")
                for other in reference if other["path"] != row["path"]
            ),
        })
    rows.sort(key=lambda row: row["candidate_id"])
    return {
        "schema": 1, "preview_byte_basis": "SI decimal, rounded display labels",
        "relationships": dict(relationships), "preview_overlaps": overlaps,
        "classification_counts": dict(Counter(row["classification"] for row in rows)),
        "zero_preview_rows": sum(row["preview_zero"] for row in rows),
        "rows": rows,
        "limitations": [
            "Historical rounded preview bytes are not measured allocated bytes or verified reclaim.",
            "Rows may overlap; no additive reclaim total is provided.",
            "Unknown paths and source-reviewed candidates carry no deletion authority.",
            "Zero preview does not establish current absence or emptiness.",
        ],
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--reference-preview", type=Path, required=True)
    parser.add_argument("--zenith-report", type=Path, required=True)
    args = parser.parse_args()
    reference, _ = parse_reference_preview(args.reference_preview)
    zenith = json.loads(args.zenith_report.read_text())
    if not isinstance(zenith.get("private_ledger"), list):
        parser.error("Zenith input must contain its private ledger")
    report = build_ledger(reference, zenith["private_ledger"], str(Path.home()))
    report["inputs"] = {
        "reference_sha256": hashlib.sha256(args.reference_preview.read_bytes()).hexdigest(),
        "zenith_sha256": hashlib.sha256(args.zenith_report.read_bytes()).hexdigest(),
        "zenith_version": zenith["version"], "started_at": zenith["started_at"],
    }
    print(json.dumps(report, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
